`isort` on the test code
Parsl/parsl pull request #3106
Opened 2024-02-23 20:55 UTC by yadudoc

# Description

`isort` **should** only resort import statements and add white spaces to separate different categories of imports.
This PR should not introduce any functional changes. I wanted to get some feedback before sticking isort on the rest of the codebase. If folks like the changes, I'd like to add this to the linter scripts.

# Changed Behaviour

No functional changes.

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Code maintenance/cleanup

2024-02-23 21:20 UTC, benclifford commented
seems fine though i didn't examine the giant diff in great detail. it would be good to run with --check-only alongside flake8, mypy so that linting-edit-wars don't arise.

2024-02-23 22:54 UTC, yadudoc commented
I checked with flake8 and there are no conflicts there. All tests are passing as well.

2024-02-23 23:01 UTC, khk-globus approved these changes
I'm personally in favor of this.  It may not be to everyone's precise liking, but it is canonical and removes the human factor of "but my way is better than your way."

In terms of making it not conflict with flake8 and other tools, there is a best-practice ordering for entry into pre-commit (or another linting tool).  I'm happy to add that, or @yadudoc it's all you.  Either way, I'm definitely, definitely in favor of adding at least flake8, pyupgrade, isort, and black into a pre-commit hook.

2024-02-24 16:15 UTC, benclifford requested changes
please introduce CI enforcement of this if you're intending to change the house style: this is going to diverge from sortedness within a few commits otherwise

2024-02-25 00:45 UTC, yadudoc commented
Fair enough. It sounds like we are agreed that this is a good idea, so here's what I'll do:
1. Replace this PR which only has isort on test code
2. Redo PR with isort on the complete code-base
3. Add isort to pre-commit
4. Add isort to linter checks

2024-02-25 19:03 UTC, benclifford commented
> Redo PR with isort on the complete code-base

slightly cynically I have some interest in what kind of import-race-conditions this uncovers...

2024-03-01 03:20 UTC, Andrew-S-Rosen commented
If you're adding `black` and `isort`, is there any reason to not just use `ruff format`?

2024-03-06 08:20 UTC, benclifford commented
given the current burst of new user/across codebase activity from Outreachy, I think don't do such a code-disrupting change as this for a few more weeks... it will break many people will outstanding changes vs `master`

2024-05-21 11:38 UTC, closed without merging