Make a Historical folder for historical files
Parsl/parsl pull request #3191
Opened 2024-03-07 12:02 UTC by SobiaAman

# Description

Make Historical folder to place historical labelled files from userguide and dev guide into it and remove it from userguide and dev guide.

# Changed Behaviour

It doesn't change flow of code

# Fixes

Fixes [3138](https://github.com/Parsl/parsl/issues/3138)

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Code maintenance/cleanup

2024-03-07 17:11 UTC, yadudoc requested changes
Hi @SobiaAman, I've made a few comments about some issues in the code. It doesn't look a historical folder/section is added which is suspect is because you probably missed adding the new folder with `git add` 

Please be careful to check the `Files changed` tab in the PR to make sure that you are not unintentionally undoing fixes that were made. I appreciate the effort put in!

2024-03-07 17:11 UTC, yadudoc commented on docs/userguide/configuring.rst
> +Blue Waters (NCSA)
This section was removed a week or so back since this machine is now retired. I'd recommend removing changes to the `configuring.rst` file.

2024-03-07 17:11 UTC, yadudoc commented on docs/userguide/execution.rst
> +2. `parsl.providers.CobaltProvider`: This provider allows you to schedule resources via the Cobalt scheduler. This Provider is DEPRECATED, and will be removed by 2024.04.
I would point out two issues here:
1. This change does not sound related to the PR title. It is good practice to keep PRs limited in scope.
2. The existing text is reasonable enough, and the new text has some odd capitalization of `provider`
So, I'd recommend removing these changes from this PR.

2024-03-07 17:11 UTC, yadudoc commented on docs/userguide/mpi_apps.rst
> +.. note::
I believe this change is unintentional because this notice was removed in the past couple of days.

2024-03-07 17:11 UTC, yadudoc commented on docs/userguide/mpi_apps.rst
> +However, it is important to not that Python Apps that directly use ``mpi4py`` is not supported.
Typo bug. This should say `note`.

2024-03-08 18:38 UTC, SobiaAman commented
> Hi @SobiaAman, I've made a few comments about some issues in the code. It doesn't look a historical folder/section is added which is suspect is because you probably missed adding the new folder with `git add`
> 
> Please be careful to check the `Files changed` tab in the PR to make sure that you are not unintentionally undoing fixes that were made. I appreciate the effort put in!

Hello @yadudoc,
You're right. Actually i did it before but at that time i was working on master branch, hence after revert the changes and working on different branches i forgot to `git add` those changes, my bad. Thanks for pointing it out. i'll take an extra care next time .

2024-03-08 21:57 UTC, yadudoc commented
@SobiaAman No problem at all. I'm closing this issue since this is fixed.

2024-03-08 21:57 UTC, closed without merging