Reduce flake8 max-line-length from 147 to 146
Parsl/parsl pull request #3228
Opened 2024-03-10 20:25 UTC by ridaaysha070

# Description

Reduced the max-line-length in flake8 from 147 to 146. Fixed the subsequent errors due to files exceeding the max-line-length.

# Changed Behaviour

# Fixes

Fixes #3105 

## Type of change

Choose which options apply, and delete the ones which do not apply.

- Code maintenance/cleanup

2024-03-14 03:17 UTC, ridaaysha070 commented
Hi @benclifford, I reduced the line length from 147 to 146 and fixed all the errors. I believe all the automated tests have also passed. Let me know if there is anything else I should add. Thanks!

2024-03-18 15:16 UTC, benclifford requested changes

2024-03-18 15:16 UTC, benclifford commented on parsl/monitoring/db_manager.py
> +                        f"Got a database OperationalError."
Missing space at the end of this string - putting two `""`-strings next to each other doesn't put a space between them, but the original message did have a space.

2024-03-18 15:16 UTC, benclifford commented on parsl/monitoring/db_manager.py
> +                        f"Got a database OperationalError."
missing space - see comment on line 665

2024-03-28 02:44 UTC, ridaaysha070 commented
@benclifford Hey, I've updated the PR to go from 146 to 145 and also fixed the spacing issues you mentioned above. Thanks again!

2024-04-09 08:19 UTC, benclifford approved these changes

2024-04-09 08:20 UTC, merged