Changed the code so it would return nothing rather than true
Parsl/parsl pull request #3238
Opened 2024-03-12 01:20 UTC by jessielin34

# Description

I fixed the issue "parsl.providers.cluster_provider _write_submit_script should return nothing, rather than constant True." I changed return True to having a placeholder of nothing. I also edited it inside of the docstring. 

# Changed Behaviour

With this new change, the return type of _write_submit_script becomes nothing or falls off the end of the method without a return statement at all.

# Fixes

Fixes #3234 

## Type of change

- Bug fix
- Code maintenance/cleanup

2024-03-12 19:41 UTC, benclifford requested changes
this PR adds a temporary file by mistake: `.deps`

2024-03-18 15:48 UTC, benclifford approved these changes

2024-03-18 15:48 UTC, merged

2024-03-18 15:48 UTC, benclifford commented
I edited the title of this pull request a bit, and merged it. thanks!

2024-03-18 16:05 UTC, jessielin34 commented
> I edited the title of this pull request a bit, and merged it. thanks!

Great, thank you!